/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remote_command.h"

commandOutput *
rexec_1_svc(commandData *argp, struct svc_req *rqstp)
{
	static commandOutput result;

	char **commandArgvs = (char**) malloc (argp->parameters.parameters_len*sizeof(char*));
	printf("%d\n", argp->parameters.parameters_len);
	for (int i=0; i<argp->parameters.parameters_len; i++) {
		commandArgvs[i] = (char*)argp->parameters.parameters_val[i];
		printf("%s\n", commandArgvs[i]);
	}
	printf("%s\n", argp->stdinBuf);

	result.statusCode = 100;
	result.stdoutBuf = (char*)"123";
	result.stderrBuf = (char*)"1234";

	return &result;
}
