/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "remote_command.h"
#include <unistd.h>
#include <stdio.h>
#include <sys/wait.h>
#include <errno.h>
#include<fcntl.h>

commandOutput *
rexec_1_svc(commandData *argp, struct svc_req *rqstp)
{
	static commandOutput result;
	int commandLen = strlen(argp->commandName)+2;

	for (int i=0; i<argp->parameters.parameters_len; i++)
		commandLen += strlen((char*)argp->parameters.parameters_val[i])+1;
	char command[commandLen];
	sprintf(command, "%s ", argp->commandName);
	for (int i=0; i<argp->parameters.parameters_len; i++)
			sprintf(command, "%s %s", command, (char*)argp->parameters.parameters_val[i]);


	int stdinFd[2], stdoutFd[2], stderrFd[2];
	pipe(stdinFd);
	pipe(stdoutFd);
	pipe(stderrFd);

	int pid;
	if((pid=fork())==0) {
		dup2(stdinFd[0], STDIN_FILENO);
		dup2(stdoutFd[1], STDOUT_FILENO);
		dup2(stderrFd[1], STDERR_FILENO);

		close(stdinFd[0]);
		close(stdoutFd[1]);
		close(stderrFd[1]);
		close(stdinFd[1]);
		close(stdoutFd[0]);
		close(stderrFd[0]);

		result.statusCode = WEXITSTATUS(system(command));
		exit(result.statusCode);
	} else {
		close(stdinFd[0]);
		close(stdoutFd[1]);
		close(stderrFd[1]);
		write(stdinFd[1], argp->stdinBuf, strlen(argp->stdinBuf)+1);
		close(stdinFd[1]);

		int status;
		waitpid(pid, &status, 0);
		result.statusCode = WEXITSTATUS(status);

		fcntl(stdoutFd[0], F_SETFL, O_NONBLOCK);
		fcntl(stderrFd[0], F_SETFL, O_NONBLOCK);
		result.stdoutBuf = (char*)malloc(sizeof(char)*1024);
		result.stderrBuf = (char*)malloc(sizeof(char)*1024);
		int count=0, stdoutBufSize=0, stderrBufSize=0;
		while((count = read(stdoutFd[0], result.stdoutBuf+stdoutBufSize, 1024))>0){
			stdoutBufSize += count;
			result.stdoutBuf = (char*)realloc(result.stdoutBuf, sizeof(char)*(stdoutBufSize+1024));
		}
		while((count = read(stderrFd[0], result.stderrBuf+stderrBufSize, 1024))>0){
			stderrBufSize += count;
			result.stderrBuf = (char*)realloc(result.stderrBuf, sizeof(char)*(stderrBufSize+1024));
		}
		result.stdoutBuf[stdoutBufSize] = 0;
		result.stderrBuf[stderrBufSize] = 0;

		return &result;
	}
}

